# Generated by Django 5.0.3 on 2024-05-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "模型",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="emoticons.mode",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emoticons.mode"
                    ),
                ),
            ],
            options={
                "verbose_name": "标签",
            },
        ),
        migrations.CreateModel(
            name="Pic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(max_length=100, verbose_name="关键词，用于搜索"),
                ),
                ("url", models.URLField(verbose_name="图片链接")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("no_words", models.BooleanField(default=False, verbose_name="无字")),
                ("blur_hash", models.CharField(max_length=256)),
                (
                    "mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pics",
                        to="emoticons.mode",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(related_name="pic_tag", to="emoticons.tag"),
                ),
            ],
            options={
                "verbose_name": "图片",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("keywords", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emoticons.category",
                    ),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="emoticons.mode",
                    ),
                ),
                (
                    "pics",
                    models.ManyToManyField(related_name="topics", to="emoticons.pic"),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="topic_tag", to="emoticons.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "话题",
            },
        ),
    ]
