# Generated by Django 5.0.3 on 2024-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emoticons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "图片标签",
                "verbose_name_plural": "图片标签",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "分类", "verbose_name_plural": "分类"},
        ),
        migrations.AlterModelOptions(
            name="mode",
            options={"verbose_name": "类型", "verbose_name_plural": "类型"},
        ),
        migrations.AlterModelOptions(
            name="pic",
            options={"verbose_name": "图片", "verbose_name_plural": "图片"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "标签", "verbose_name_plural": "标签"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "话题", "verbose_name_plural": "话题"},
        ),
        migrations.AlterField(
            model_name="pic",
            name="tags",
            field=models.ManyToManyField(related_name="pic_tag", to="emoticons.ptag"),
        ),
    ]
