# Generated by Django 5.0.3 on 2024-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emoticons", "0002_ptag_alter_category_options_alter_mode_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pic",
            name="blur_hash",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
