# Generated by Django 5.0.3 on 2024-05-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emoticons", "0003_alter_pic_blur_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pic",
            name="keywords",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="关键词，用于搜索"
            ),
        ),
    ]
